# Name displayed during Bluetooth scan
CONFIG_ZMK_KEYBOARD_NAME="Left Gamepad"

# Standalone mode (prevents waiting for a split second-half)
CONFIG_ZMK_SPLIT=n

# Enable Bluetooth & Power Management
CONFIG_ZMK_BLE=y
CONFIG_ZMK_SLEEP=y

# Boost Bluetooth transmit power to maximum (+8 dBm) for better range/signal
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Experimental features for improved Bluetooth stability
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
